/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "logger.h"
#include <string.h>
#include <stdio.h>

bool_t
log_operation_1_svc(log_entry arg1, int *result,  struct svc_req *rqstp)
{
	bool_t retval = TRUE;

	//imprimir con formato adecuado
	if (strcmp(arg1.operation, "PUBLISH") == 0 || strcmp(arg1.operation, "DELETE") == 0) {
		// si la operacion es publish o delete hay que imprimir el filename tambien
		printf("%s %s %s %s\n", arg1.user_name, arg1.operation, arg1.file_name, arg1.datetime);
	} else {
		// si no es publish o delete no se imprimer filename
		printf("%s %s %s\n", arg1.user_name, arg1.operation, arg1.datetime);
	}

	fflush(stdout); // asegurar impresion 

	*result = 0;

	return retval;
}

int
logger_prog_1_freeresult (SVCXPRT *transp, xdrproc_t xdr_result, caddr_t result)
{
	xdr_free (xdr_result, result);

	/*
	 * Insert additional freeing code here, if needed
	 */

	return 1;
}
